version: "3.8"

services:
  postgres:
    image: postgres:16.3-alpine3.20
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gists
    ports:
      - 5432:5432
    volumes:
      - gists-db-vol:/var/lib/postgresql/data
volumes:
  gists-db-vol:
