DROP TABLE IF EXISTS auth_identity;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS users_auth;
DROP TABLE IF EXISTS token;
DROP TABLE IF EXISTS users_token;

ALTER TABLE gists DROP COLUMN owner;
ALTER TABLE gists DROP CONSTRAINT fk_owner;
