name: Deploy
on:
  release:
    types: [created]

permissions:
  contents: read

jobs:
  get_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo "tag=$GITHUB_REF" | sed s/"refs\/tags\/v/"/g >> $GITHUB_OUTPUT
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}
  deploy:
    name: deploy_project
    runs-on: ubuntu-latest
    needs: get_tag
    env:
      TAG: ${{ needs.get_tag.outputs.tag }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          repository: Courtcircuits/cluster
          token: "${{ secrets.DEPLOYMENT_TOKEN }}"
      - name: Update values.yaml
        run: |
          sudo add-apt-repository ppa:rmescandon/yq
          sudo apt update
          sudo apt install yq -y
          cd projects/gists/gists
          yq eval -i '.tag = env(TAG)' tag.yaml
          git config --global user.name "GIST Bot"
          git config --global user.email "ci.deployment.gists@users.noreply.github.com"
          git add tag.yaml
          git commit -m "api gist | ${{ env.TAG }} | ${{ github.event.head_commit.message }}"
          git push
