name: Continuous testing
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Integration tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: gists
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      PORT:"4000"
      PG_USER:"postgres"
      PG_PASSWORD:"postgres"
      PG_PORT:"5432"
      PG_HOST:"0.0.0.0"
      PG_DATABASE:"gists"
      GOOGLE_KEY:""
      GOOGLE_SECRET:""
      GITHUB_KEY:""
      GITHUB_SECRET:""
      PUBLIC_URL:"http://localhost:4000"
      APP_KEY:"DUMP_APP_KEY_FOR_TEST"
      SMTP_HOST:""
      MAIL_SMTP:""
      MAIL_PASSWORD:""
      SMTP_PORT:""
      FRONTEND_URL:"http://localhost:3000"
    steps:
      - uses: actions/checkout@v4
      - name: Install Go toolchain
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: 1.23.0
      - name: Run migrations
        run: go build -o main && chmod +x ./main && ./main migrate
      - name: Run tests
        run: go test ./tests/
