name: Trivy Scan

on:
  pull_request:
    branches:
      - main

jobs:
  trivy-scan:
    name: Trivy - Docker Image & Code Scan
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker (optional, ensures clean setup)
        run: docker system prune -af

      - name: Build Docker image locally
        run: docker build -t gistsapp/api:${{ github.sha }} .

      - name: Run Trivy image scan
        id: trivy_image
        continue-on-error: true
        uses: aquasecurity/trivy-action@0.31.0
        with:
          image-ref: 'gistsapp/api:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Run Trivy filesystem scan
        id: trivy_fs
        continue-on-error: true
        uses: aquasecurity/trivy-action@0.31.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Fail job if any Trivy scan failed
        run: |
          if [ "${{ steps.trivy_image.outcome }}" != "success" ] || [ "${{ steps.trivy_fs.outcome }}" != "success" ]; then
            echo "❌ One or both Trivy scans failed."
            exit 1
          else
            echo "✅ Both Trivy scans passed."
          fi
